name: ClearLagg
main: ClearLagg\Main
version: 1.0.0-Beta
api: [5.0.0]
load: POSTWORLD
author: NurAzliYT, XPocketMC
description: A plugin to reduce lag by clearing dropped items.
commands:
  clearlagg:
    description: Clears all dropped items.
    usage: "/clearlagg [stats]"
    permission: clearlagg.use
permissions:
  clearlagg.use:
    default: true
    description: Allows the player to use the clearlagg command.
  clearlagg.stats:
    default: true
    description: Allows the player to view clearlagg statistics.
